import type {
  FacultyDashboardResponse,
  FacultyLeaveRequest,
} from '@/queries/faculty.ts';
import {
  formatCompactHours,
  formatLongDate,
  formatLongDateRange,
  formatMonth,
} from './FacultyDashboardPanels.tsx';
import { Modal } from './FacultyDashboardModal.tsx';

type EmailPreviewData = {
  body: string;
  cc: string;
  requestId: string;
  subject: string;
  to: string;
};

function buildMockCcEmail(faculty: FacultyDashboardResponse['faculty']) {
  if (faculty.departmentCode) {
    return `${faculty.departmentCode.toLowerCase()}@ucdavis.edu`;
  }

  if (faculty.email) {
    return faculty.email;
  }

  return 'faculty-notifications@ucdavis.edu';
}

function buildDraftEmailPreview(
  faculty: FacultyDashboardResponse['faculty'],
  draft: {
    endDate: string;
    leaveTypeLabel: string;
    note: string | null;
    startDate: string;
    totalHours: number;
  }
): EmailPreviewData {
  const requestId = `r${Date.now()}`;
  const departmentName = faculty.departmentName ?? 'Unknown Department';
  const subject = `CAES Faculty Leave Report - ${faculty.name} - ${departmentName} - ${formatMonth(draft.startDate)}`;
  const note = draft.note ?? 'N/A';
  const submittedAt = new Intl.DateTimeFormat(undefined, {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  }).format(new Date());

  return {
    body: [
      'Faculty Leave Report Submission',
      '==============================',
      `Name: ${faculty.name}`,
      `Email: ${faculty.email ?? 'N/A'}`,
      `Department: ${departmentName}`,
      `Position: ${faculty.jobTitle ?? faculty.employeeClass ?? 'N/A'}`,
      '',
      'Leave Details:',
      `  Type: ${draft.leaveTypeLabel}`,
      `  Date(s): ${formatLongDateRange(draft.startDate, draft.endDate)}`,
      `  Total Hours: ${formatCompactHours(draft.totalHours)}`,
      `  Note: ${note}`,
      '',
      `Submission Date: ${submittedAt}`,
      '',
      '---',
      'Auto-generated by HERD (Hours Entry, Reporting & Debit)',
      `Request ID: ${requestId}`,
    ].join('\n'),
    cc: buildMockCcEmail(faculty),
    requestId,
    subject,
    to: 'aggieservice@ucdavis.edu',
  };
}

function buildExistingRequestEmailPreview(
  faculty: FacultyDashboardResponse['faculty'],
  request: FacultyLeaveRequest
): EmailPreviewData {
  const requestId = `r${request.id}`;
  const subject = `CAES Faculty Leave Report - ${faculty.name} - ${request.departmentName} - ${formatMonth(request.startDate)}`;

  return {
    body: [
      'Faculty Leave Report Submission',
      '==============================',
      `Name: ${faculty.name}`,
      `Email: ${faculty.email ?? 'N/A'}`,
      `Department: ${request.departmentName}`,
      `Position: ${faculty.jobTitle ?? faculty.employeeClass ?? 'N/A'}`,
      '',
      'Leave Details:',
      `  Type: ${request.leaveType}`,
      `  Date(s): ${formatLongDateRange(request.startDate, request.endDate)}`,
      `  Total Hours: ${formatCompactHours(request.totalHours)}`,
      `  Note: ${request.note?.trim() || 'N/A'}`,
      '',
      `Submission Date: ${formatLongDate(request.submittedAt)}`,
      '',
      '---',
      'Auto-generated by HERD (Hours Entry, Reporting & Debit)',
      `Request ID: ${requestId}`,
    ].join('\n'),
    cc: buildMockCcEmail(faculty),
    requestId,
    subject,
    to: 'aggieservice@ucdavis.edu',
  };
}

function EmailPreviewModal({
  onClose,
  onPrimaryAction,
  onSecondaryAction,
  preview,
  primaryLabel,
  primaryLoading,
  secondaryLabel,
  statusMessage,
  title,
}: {
  onClose: () => void;
  onPrimaryAction: () => void;
  onSecondaryAction?: (() => void) | null;
  preview: EmailPreviewData;
  primaryLabel: string;
  primaryLoading?: boolean;
  secondaryLabel: string | null;
  statusMessage?: string | null;
  title: string;
}) {
  return (
    <Modal onClose={onClose} title={title}>
      <div className="space-y-5">
        <dl className="space-y-2 text-sm">
          <div>
            <dt className="inline font-bold">To:</dt>{' '}
            <dd className="inline">{preview.to}</dd>
          </div>
          <div>
            <dt className="inline font-bold">CC:</dt>{' '}
            <dd className="inline">{preview.cc}</dd>
          </div>
          <div>
            <dt className="inline font-bold">Subject:</dt>{' '}
            <dd className="inline">{preview.subject}</dd>
          </div>
        </dl>

        <textarea
          className="textarea textarea-bordered min-h-80 w-full font-mono text-sm"
          readOnly
          value={preview.body}
        />

        <div className="text-sm text-base-content/70">
          Mock mode - email will be simulated
        </div>

        {statusMessage ? (
          <div
            className="rounded-lg border border-error/30 bg-error/10 px-4 py-3 text-sm text-error"
            role="alert"
          >
            {statusMessage}
          </div>
        ) : null}

        <div className="flex justify-end gap-3">
          {secondaryLabel ? (
            <button
              className="btn btn-outline btn-primary"
              onClick={onSecondaryAction ?? undefined}
              type="button"
            >
              {secondaryLabel}
            </button>
          ) : null}
          <button
            className="btn btn-primary min-w-36"
            disabled={primaryLoading}
            onClick={onPrimaryAction}
            type="button"
          >
            {primaryLoading ? 'Sending...' : primaryLabel}
          </button>
        </div>
      </div>
    </Modal>
  );
}

export function DraftEmailPreviewModal({
  draft,
  faculty,
  onClose,
  onPrimaryAction,
  onSecondaryAction,
  primaryLabel,
  primaryLoading,
  secondaryLabel,
  statusMessage,
}: {
  draft: {
    endDate: string;
    leaveTypeLabel: string;
    note: string | null;
    startDate: string;
    totalHours: number;
  };
  faculty: FacultyDashboardResponse['faculty'];
  onClose: () => void;
  onPrimaryAction: () => void;
  onSecondaryAction?: (() => void) | null;
  primaryLabel: string;
  primaryLoading?: boolean;
  secondaryLabel: string | null;
  statusMessage?: string | null;
}) {
  return (
    <EmailPreviewModal
      onClose={onClose}
      onPrimaryAction={onPrimaryAction}
      onSecondaryAction={onSecondaryAction}
      preview={buildDraftEmailPreview(faculty, draft)}
      primaryLabel={primaryLabel}
      primaryLoading={primaryLoading}
      secondaryLabel={secondaryLabel}
      statusMessage={statusMessage}
      title="Email Preview: AggieService Submission"
    />
  );
}

export function ExistingRequestEmailPreviewModal({
  faculty,
  onClose,
  onPrimaryAction,
  onSecondaryAction,
  primaryLabel,
  primaryLoading,
  request,
  secondaryLabel,
}: {
  faculty: FacultyDashboardResponse['faculty'];
  onClose: () => void;
  onPrimaryAction: () => void;
  onSecondaryAction?: (() => void) | null;
  primaryLabel: string;
  primaryLoading?: boolean;
  request: FacultyLeaveRequest;
  secondaryLabel: string | null;
}) {
  return (
    <EmailPreviewModal
      onClose={onClose}
      onPrimaryAction={onPrimaryAction}
      onSecondaryAction={onSecondaryAction}
      preview={buildExistingRequestEmailPreview(faculty, request)}
      primaryLabel={primaryLabel}
      primaryLoading={primaryLoading}
      secondaryLabel={secondaryLabel}
      title="Email Preview: AggieService Submission"
    />
  );
}
