/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as authenticatedTeamCalendarRouteImport } from './routes/(authenticated)/team-calendar'
import { Route as authenticatedHistoryRouteImport } from './routes/(authenticated)/history'
import { Route as authenticatedApprovalsRouteImport } from './routes/(authenticated)/approvals'
import { Route as authenticatedAdminRouteImport } from './routes/(authenticated)/admin'
import { Route as authenticatedAdminIndexRouteImport } from './routes/(authenticated)/admin.index'
import { Route as authenticatedFacultyIamIdRouteImport } from './routes/(authenticated)/faculty.$iamId'
import { Route as authenticatedAdminStatusRouteImport } from './routes/(authenticated)/admin.status'
import { Route as authenticatedAdminManageUsersRouteImport } from './routes/(authenticated)/admin.manage-users'
import { Route as authenticatedAdminFacultyRouteImport } from './routes/(authenticated)/admin.faculty'
import { Route as authenticatedAdminDepartmentsRouteImport } from './routes/(authenticated)/admin.departments'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedTeamCalendarRoute =
  authenticatedTeamCalendarRouteImport.update({
    id: '/team-calendar',
    path: '/team-calendar',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedHistoryRoute = authenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedApprovalsRoute = authenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedAdminRoute = authenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedAdminIndexRoute = authenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedAdminRoute,
} as any)
const authenticatedFacultyIamIdRoute =
  authenticatedFacultyIamIdRouteImport.update({
    id: '/faculty/$iamId',
    path: '/faculty/$iamId',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAdminStatusRoute =
  authenticatedAdminStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => authenticatedAdminRoute,
  } as any)
const authenticatedAdminManageUsersRoute =
  authenticatedAdminManageUsersRouteImport.update({
    id: '/manage-users',
    path: '/manage-users',
    getParentRoute: () => authenticatedAdminRoute,
  } as any)
const authenticatedAdminFacultyRoute =
  authenticatedAdminFacultyRouteImport.update({
    id: '/faculty',
    path: '/faculty',
    getParentRoute: () => authenticatedAdminRoute,
  } as any)
const authenticatedAdminDepartmentsRoute =
  authenticatedAdminDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => authenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof authenticatedAdminRouteWithChildren
  '/approvals': typeof authenticatedApprovalsRoute
  '/history': typeof authenticatedHistoryRoute
  '/team-calendar': typeof authenticatedTeamCalendarRoute
  '/': typeof authenticatedIndexRoute
  '/admin/departments': typeof authenticatedAdminDepartmentsRoute
  '/admin/faculty': typeof authenticatedAdminFacultyRoute
  '/admin/manage-users': typeof authenticatedAdminManageUsersRoute
  '/admin/status': typeof authenticatedAdminStatusRoute
  '/faculty/$iamId': typeof authenticatedFacultyIamIdRoute
  '/admin/': typeof authenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/approvals': typeof authenticatedApprovalsRoute
  '/history': typeof authenticatedHistoryRoute
  '/team-calendar': typeof authenticatedTeamCalendarRoute
  '/': typeof authenticatedIndexRoute
  '/admin/departments': typeof authenticatedAdminDepartmentsRoute
  '/admin/faculty': typeof authenticatedAdminFacultyRoute
  '/admin/manage-users': typeof authenticatedAdminManageUsersRoute
  '/admin/status': typeof authenticatedAdminStatusRoute
  '/faculty/$iamId': typeof authenticatedFacultyIamIdRoute
  '/admin': typeof authenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/admin': typeof authenticatedAdminRouteWithChildren
  '/(authenticated)/approvals': typeof authenticatedApprovalsRoute
  '/(authenticated)/history': typeof authenticatedHistoryRoute
  '/(authenticated)/team-calendar': typeof authenticatedTeamCalendarRoute
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/(authenticated)/admin/departments': typeof authenticatedAdminDepartmentsRoute
  '/(authenticated)/admin/faculty': typeof authenticatedAdminFacultyRoute
  '/(authenticated)/admin/manage-users': typeof authenticatedAdminManageUsersRoute
  '/(authenticated)/admin/status': typeof authenticatedAdminStatusRoute
  '/(authenticated)/faculty/$iamId': typeof authenticatedFacultyIamIdRoute
  '/(authenticated)/admin/': typeof authenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/approvals'
    | '/history'
    | '/team-calendar'
    | '/'
    | '/admin/departments'
    | '/admin/faculty'
    | '/admin/manage-users'
    | '/admin/status'
    | '/faculty/$iamId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/approvals'
    | '/history'
    | '/team-calendar'
    | '/'
    | '/admin/departments'
    | '/admin/faculty'
    | '/admin/manage-users'
    | '/admin/status'
    | '/faculty/$iamId'
    | '/admin'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(authenticated)/admin'
    | '/(authenticated)/approvals'
    | '/(authenticated)/history'
    | '/(authenticated)/team-calendar'
    | '/(authenticated)/'
    | '/(authenticated)/admin/departments'
    | '/(authenticated)/admin/faculty'
    | '/(authenticated)/admin/manage-users'
    | '/(authenticated)/admin/status'
    | '/(authenticated)/faculty/$iamId'
    | '/(authenticated)/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/team-calendar': {
      id: '/(authenticated)/team-calendar'
      path: '/team-calendar'
      fullPath: '/team-calendar'
      preLoaderRoute: typeof authenticatedTeamCalendarRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/history': {
      id: '/(authenticated)/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof authenticatedHistoryRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/approvals': {
      id: '/(authenticated)/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof authenticatedApprovalsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/admin': {
      id: '/(authenticated)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authenticatedAdminRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/admin/': {
      id: '/(authenticated)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof authenticatedAdminIndexRouteImport
      parentRoute: typeof authenticatedAdminRoute
    }
    '/(authenticated)/faculty/$iamId': {
      id: '/(authenticated)/faculty/$iamId'
      path: '/faculty/$iamId'
      fullPath: '/faculty/$iamId'
      preLoaderRoute: typeof authenticatedFacultyIamIdRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/admin/status': {
      id: '/(authenticated)/admin/status'
      path: '/status'
      fullPath: '/admin/status'
      preLoaderRoute: typeof authenticatedAdminStatusRouteImport
      parentRoute: typeof authenticatedAdminRoute
    }
    '/(authenticated)/admin/manage-users': {
      id: '/(authenticated)/admin/manage-users'
      path: '/manage-users'
      fullPath: '/admin/manage-users'
      preLoaderRoute: typeof authenticatedAdminManageUsersRouteImport
      parentRoute: typeof authenticatedAdminRoute
    }
    '/(authenticated)/admin/faculty': {
      id: '/(authenticated)/admin/faculty'
      path: '/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof authenticatedAdminFacultyRouteImport
      parentRoute: typeof authenticatedAdminRoute
    }
    '/(authenticated)/admin/departments': {
      id: '/(authenticated)/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof authenticatedAdminDepartmentsRouteImport
      parentRoute: typeof authenticatedAdminRoute
    }
  }
}

interface authenticatedAdminRouteChildren {
  authenticatedAdminDepartmentsRoute: typeof authenticatedAdminDepartmentsRoute
  authenticatedAdminFacultyRoute: typeof authenticatedAdminFacultyRoute
  authenticatedAdminManageUsersRoute: typeof authenticatedAdminManageUsersRoute
  authenticatedAdminStatusRoute: typeof authenticatedAdminStatusRoute
  authenticatedAdminIndexRoute: typeof authenticatedAdminIndexRoute
}

const authenticatedAdminRouteChildren: authenticatedAdminRouteChildren = {
  authenticatedAdminDepartmentsRoute: authenticatedAdminDepartmentsRoute,
  authenticatedAdminFacultyRoute: authenticatedAdminFacultyRoute,
  authenticatedAdminManageUsersRoute: authenticatedAdminManageUsersRoute,
  authenticatedAdminStatusRoute: authenticatedAdminStatusRoute,
  authenticatedAdminIndexRoute: authenticatedAdminIndexRoute,
}

const authenticatedAdminRouteWithChildren =
  authenticatedAdminRoute._addFileChildren(authenticatedAdminRouteChildren)

interface authenticatedRouteRouteChildren {
  authenticatedAdminRoute: typeof authenticatedAdminRouteWithChildren
  authenticatedApprovalsRoute: typeof authenticatedApprovalsRoute
  authenticatedHistoryRoute: typeof authenticatedHistoryRoute
  authenticatedTeamCalendarRoute: typeof authenticatedTeamCalendarRoute
  authenticatedIndexRoute: typeof authenticatedIndexRoute
  authenticatedFacultyIamIdRoute: typeof authenticatedFacultyIamIdRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedAdminRoute: authenticatedAdminRouteWithChildren,
  authenticatedApprovalsRoute: authenticatedApprovalsRoute,
  authenticatedHistoryRoute: authenticatedHistoryRoute,
  authenticatedTeamCalendarRoute: authenticatedTeamCalendarRoute,
  authenticatedIndexRoute: authenticatedIndexRoute,
  authenticatedFacultyIamIdRoute: authenticatedFacultyIamIdRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
