/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as authenticatedAdminRouteImport } from './routes/(authenticated)/admin'
import { Route as authenticatedAdminUsersRouteImport } from './routes/(authenticated)/admin.users'
import { Route as authenticatedAdminStatusRouteImport } from './routes/(authenticated)/admin.status'
import { Route as authenticatedAdminDepartmentsRouteImport } from './routes/(authenticated)/admin.departments'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedAdminRoute = authenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedAdminUsersRoute = authenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => authenticatedAdminRoute,
} as any)
const authenticatedAdminStatusRoute =
  authenticatedAdminStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => authenticatedAdminRoute,
  } as any)
const authenticatedAdminDepartmentsRoute =
  authenticatedAdminDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => authenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof authenticatedAdminRouteWithChildren
  '/': typeof authenticatedIndexRoute
  '/admin/departments': typeof authenticatedAdminDepartmentsRoute
  '/admin/status': typeof authenticatedAdminStatusRoute
  '/admin/users': typeof authenticatedAdminUsersRoute
}
export interface FileRoutesByTo {
  '/admin': typeof authenticatedAdminRouteWithChildren
  '/': typeof authenticatedIndexRoute
  '/admin/departments': typeof authenticatedAdminDepartmentsRoute
  '/admin/status': typeof authenticatedAdminStatusRoute
  '/admin/users': typeof authenticatedAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/admin': typeof authenticatedAdminRouteWithChildren
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/(authenticated)/admin/departments': typeof authenticatedAdminDepartmentsRoute
  '/(authenticated)/admin/status': typeof authenticatedAdminStatusRoute
  '/(authenticated)/admin/users': typeof authenticatedAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/admin/departments'
    | '/admin/status'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin' | '/' | '/admin/departments' | '/admin/status' | '/admin/users'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(authenticated)/admin'
    | '/(authenticated)/'
    | '/(authenticated)/admin/departments'
    | '/(authenticated)/admin/status'
    | '/(authenticated)/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/admin': {
      id: '/(authenticated)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authenticatedAdminRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/admin/users': {
      id: '/(authenticated)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof authenticatedAdminUsersRouteImport
      parentRoute: typeof authenticatedAdminRoute
    }
    '/(authenticated)/admin/status': {
      id: '/(authenticated)/admin/status'
      path: '/status'
      fullPath: '/admin/status'
      preLoaderRoute: typeof authenticatedAdminStatusRouteImport
      parentRoute: typeof authenticatedAdminRoute
    }
    '/(authenticated)/admin/departments': {
      id: '/(authenticated)/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof authenticatedAdminDepartmentsRouteImport
      parentRoute: typeof authenticatedAdminRoute
    }
  }
}

interface authenticatedAdminRouteChildren {
  authenticatedAdminDepartmentsRoute: typeof authenticatedAdminDepartmentsRoute
  authenticatedAdminStatusRoute: typeof authenticatedAdminStatusRoute
  authenticatedAdminUsersRoute: typeof authenticatedAdminUsersRoute
}

const authenticatedAdminRouteChildren: authenticatedAdminRouteChildren = {
  authenticatedAdminDepartmentsRoute: authenticatedAdminDepartmentsRoute,
  authenticatedAdminStatusRoute: authenticatedAdminStatusRoute,
  authenticatedAdminUsersRoute: authenticatedAdminUsersRoute,
}

const authenticatedAdminRouteWithChildren =
  authenticatedAdminRoute._addFileChildren(authenticatedAdminRouteChildren)

interface authenticatedRouteRouteChildren {
  authenticatedAdminRoute: typeof authenticatedAdminRouteWithChildren
  authenticatedIndexRoute: typeof authenticatedIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedAdminRoute: authenticatedAdminRouteWithChildren,
  authenticatedIndexRoute: authenticatedIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
