// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Core.Data;

#nullable disable

namespace server.core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717181106_AddCoreDomainTables")]
    partial class AddCoreDomainTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Core.Domain.AppAdminAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppAdminAssignmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IamId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("IamId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppAdminAssignment_IamId");

                    b.ToTable("AppAdminAssignment");
                });

            modelBuilder.Entity("Server.Core.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)");

                    b.Property<Guid>("EntraObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FirstLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IamId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_AppUser_Email");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUser_EmployeeId")
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("EntraObjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUser_EntraObjectId");

                    b.HasIndex("IamId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUser_IamId")
                        .HasFilter("[IamId] IS NOT NULL");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("Server.Core.Domain.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClusterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.ToTable("Cluster");
                });

            modelBuilder.Entity("Server.Core.Domain.ClusterCaoAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClosedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClusterId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EffectiveEndDateExclusive")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveStartDate")
                        .HasColumnType("date");

                    b.Property<string>("IamId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByAppUserId");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("IamId")
                        .HasDatabaseName("IX_CaoAssignment_IamId");

                    b.HasIndex("ClusterId", "EffectiveStartDate", "EffectiveEndDateExclusive")
                        .HasDatabaseName("IX_CaoAssignment_Cluster_EffectiveDates");

                    b.ToTable("ClusterCaoAssignment");
                });

            modelBuilder.Entity("Server.Core.Domain.Department", b =>
                {
                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ClusterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastSeenInSourceAt")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("SourceLevel")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkflowMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("DepartmentCode");

                    b.HasIndex("ClusterId")
                        .HasDatabaseName("IX_Department_ClusterId");

                    b.HasIndex("LastSeenInSourceAt")
                        .HasDatabaseName("IX_Department_LastSeenInSourceAt");

                    b.HasIndex("WorkflowMode")
                        .HasDatabaseName("IX_Department_WorkflowMode");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Server.Core.Domain.DepartmentChairAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClosedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly?>("EffectiveEndDateExclusive")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveStartDate")
                        .HasColumnType("date");

                    b.Property<string>("IamId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByAppUserId");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("IamId")
                        .HasDatabaseName("IX_ChairAssignment_IamId");

                    b.HasIndex("DepartmentCode", "EffectiveStartDate", "EffectiveEndDateExclusive")
                        .HasDatabaseName("IX_ChairAssignment_Department_EffectiveDates");

                    b.ToTable("DepartmentChairAssignment");
                });

            modelBuilder.Entity("Server.Core.Domain.DepartmentEmailRouting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("UpdatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode")
                        .HasDatabaseName("IX_DepartmentEmailRouting_DepartmentCode");

                    b.HasIndex("UpdatedByAppUserId");

                    b.HasIndex("DepartmentCode", "ToEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_DepartmentEmailRouting_DepartmentCode_ToEmail");

                    b.ToTable("DepartmentEmailRouting");
                });

            modelBuilder.Entity("Server.Core.Domain.EmployeeAccrualBalance", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<string>("PositionNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("LeaveTypeNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("AccrualHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AccrualLimit")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AccrualPercentage")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("AdjustedHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ApproachingMax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CalculatedBal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EmployeeClassCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("EmployeeClassDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeStatusDescription")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeTypeDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ExceptionalMaxVacationOnly")
                        .HasColumnType("int");

                    b.Property<decimal>("HourlyRateFTE")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("HoursOverUnderPolicyMax")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HoursTaken")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HrStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("JobCodeDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastUpdated")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Level1Dept")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Level1DeptDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Level2Dept")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Level2DeptDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Level3Dept")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Level3DeptDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Level4Dept")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Level4DeptDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Level5Dept")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Level5DeptDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LoadDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("PrevBal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ReportsToEmployeeId")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("ReportsToEmployeeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReportsToPositionNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("TypeLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnionCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("UnionDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId", "AsOfDate", "PositionNumber", "LeaveTypeNumber")
                        .HasName("PK_EmployeeAccrualBalances");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_EmployeeAccrualBalances_EmployeeId");

                    b.HasIndex("AsOfDate", "EmployeeId", "LeaveTypeNumber")
                        .HasDatabaseName("IX_EmployeeAccrualBalances_AsOf_Employee_LeaveType");

                    b.ToTable("EmployeeAccrualBalances", "dbo");
                });

            modelBuilder.Entity("Server.Core.Domain.EmployeeReportingDepartmentOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeReportingDepartmentOverrideId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClosedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly?>("EffectiveEndDateExclusive")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveStartDate")
                        .HasColumnType("date");

                    b.Property<string>("IamId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByAppUserId");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("DepartmentCode")
                        .HasDatabaseName("IX_ReportingDeptOverride_DepartmentCode");

                    b.HasIndex("IamId", "EffectiveStartDate", "EffectiveEndDateExclusive")
                        .HasDatabaseName("IX_ReportingDeptOverride_IamId_EffectiveDates");

                    b.ToTable("EmployeeReportingDepartmentOverride");
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ClusterIdSnapshot")
                        .HasColumnType("int");

                    b.Property<string>("CoveragePlan")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("IamId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PayLeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ReportingDepartmentCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ReportingDepartmentNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkflowModeSnapshot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .HasDatabaseName("IX_LeaveRequest_AppUserId");

                    b.HasIndex("IamId")
                        .HasDatabaseName("IX_LeaveRequest_IamId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("PayLeaveTypeId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_LeaveRequest_Status");

                    b.HasIndex("ReportingDepartmentCodeSnapshot", "Status")
                        .HasDatabaseName("IX_LeaveRequest_Department_Status");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_LeaveRequest_DateRange");

                    b.ToTable("LeaveRequest");
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveRequestAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int>("ActorAppUserId")
                        .HasColumnType("int");

                    b.Property<string>("ActorIamId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsSelfAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LeaveRequestId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActionAt")
                        .HasDatabaseName("IX_LeaveRequestAction_ActionAt");

                    b.HasIndex("ActorAppUserId")
                        .HasDatabaseName("IX_LeaveRequestAction_ActorAppUserId");

                    b.HasIndex("LeaveRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_LeaveRequestAction_LeaveRequestId");

                    b.ToTable("LeaveRequestAction");
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveRequestDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("LeaveDate")
                        .HasColumnType("date");

                    b.Property<int>("LeaveRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaveDate")
                        .HasDatabaseName("IX_LeaveRequestDay_LeaveDate");

                    b.HasIndex("LeaveRequestId", "LeaveDate")
                        .IsUnique()
                        .HasDatabaseName("UX_LeaveRequestDay_Request_Date");

                    b.ToTable("LeaveRequestDay");
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HasAccrualBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LeaveTypeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SourceLeaveTypeNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeKey")
                        .IsUnique()
                        .HasDatabaseName("UX_LeaveType_LeaveTypeKey");

                    b.HasIndex("SourceLeaveTypeNumber")
                        .HasDatabaseName("IX_LeaveType_SourceLeaveTypeNumber");

                    b.ToTable("LeaveType");
                });

            modelBuilder.Entity("Server.Core.Domain.OutboundMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("LeaveRequestId")
                        .HasColumnType("int");

                    b.Property<Guid?>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NotBeforeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime?>("SentUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc")
                        .HasDatabaseName("IX_OutboundMessage_CreatedUtc");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("UX_OutboundMessage_DedupeKey");

                    b.HasIndex("LeaveRequestId")
                        .HasDatabaseName("IX_OutboundMessage_LeaveRequestId");

                    b.HasIndex("NotificationType")
                        .HasDatabaseName("IX_OutboundMessage_NotificationType");

                    b.HasIndex("Status", "NotBeforeUtc", "LockedUntilUtc")
                        .HasDatabaseName("IX_OutboundMessage_Status_NotBefore_LockedUntil");

                    b.ToTable("OutboundMessage");
                });

            modelBuilder.Entity("Server.Core.Domain.Person", b =>
                {
                    b.Property<string>("IamId")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<DateTime?>("FirstIngestedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FullName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("IsCampusEmployee")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<bool?>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFaculty")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsHsEmployee")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsStaff")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsStudent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LastRunId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("ModifyDateRaw")
                        .HasMaxLength(19)
                        .HasColumnType("char(19)");

                    b.Property<string>("PrivacyCode")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("PromotedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("PromotionRunId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    b.Property<string>("Pronouns")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SourceEndpoint")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("StudentId")
                        .HasMaxLength(9)
                        .HasColumnType("char(9)");

                    b.Property<string>("Suffix")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("UserId")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)");

                    b.HasKey("IamId");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_People_EmployeeId");

                    b.ToTable("People", "dbo");
                });

            modelBuilder.Entity("Server.Core.Domain.AppAdminAssignment", b =>
                {
                    b.HasOne("Server.Core.Domain.AppUser", "CreatedByAppUser")
                        .WithMany("CreatedAdminAssignments")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByAppUser");
                });

            modelBuilder.Entity("Server.Core.Domain.Cluster", b =>
                {
                    b.HasOne("Server.Core.Domain.AppUser", "CreatedByAppUser")
                        .WithMany("CreatedClusters")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByAppUser");
                });

            modelBuilder.Entity("Server.Core.Domain.ClusterCaoAssignment", b =>
                {
                    b.HasOne("Server.Core.Domain.AppUser", "ClosedByAppUser")
                        .WithMany("ClosedClusterCaoAssignments")
                        .HasForeignKey("ClosedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Core.Domain.Cluster", "Cluster")
                        .WithMany("ClusterCaoAssignments")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.AppUser", "CreatedByAppUser")
                        .WithMany("CreatedClusterCaoAssignments")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClosedByAppUser");

                    b.Navigation("Cluster");

                    b.Navigation("CreatedByAppUser");
                });

            modelBuilder.Entity("Server.Core.Domain.Department", b =>
                {
                    b.HasOne("Server.Core.Domain.Cluster", "Cluster")
                        .WithMany("Departments")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("Server.Core.Domain.DepartmentChairAssignment", b =>
                {
                    b.HasOne("Server.Core.Domain.AppUser", "ClosedByAppUser")
                        .WithMany("ClosedDepartmentChairAssignments")
                        .HasForeignKey("ClosedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Core.Domain.AppUser", "CreatedByAppUser")
                        .WithMany("CreatedDepartmentChairAssignments")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.Department", "Department")
                        .WithMany("DepartmentChairAssignments")
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClosedByAppUser");

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Server.Core.Domain.DepartmentEmailRouting", b =>
                {
                    b.HasOne("Server.Core.Domain.Department", null)
                        .WithMany("DepartmentEmailRoutings")
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.AppUser", null)
                        .WithMany("UpdatedDepartmentEmailRoutings")
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Core.Domain.EmployeeReportingDepartmentOverride", b =>
                {
                    b.HasOne("Server.Core.Domain.AppUser", "ClosedByAppUser")
                        .WithMany("ClosedEmployeeReportingDepartmentOverrides")
                        .HasForeignKey("ClosedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Core.Domain.AppUser", "CreatedByAppUser")
                        .WithMany("CreatedEmployeeReportingDepartmentOverrides")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.Department", "Department")
                        .WithMany("EmployeeReportingDepartmentOverrides")
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClosedByAppUser");

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveRequest", b =>
                {
                    b.HasOne("Server.Core.Domain.AppUser", null)
                        .WithMany("LeaveRequests")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.LeaveType", null)
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.LeaveType", null)
                        .WithMany("PayLeaveRequests")
                        .HasForeignKey("PayLeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveRequestAction", b =>
                {
                    b.HasOne("Server.Core.Domain.AppUser", null)
                        .WithMany("LeaveRequestActions")
                        .HasForeignKey("ActorAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.LeaveRequest", null)
                        .WithMany("Actions")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveRequestDay", b =>
                {
                    b.HasOne("Server.Core.Domain.LeaveRequest", "LeaveRequest")
                        .WithMany("Days")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveRequest");
                });

            modelBuilder.Entity("Server.Core.Domain.OutboundMessage", b =>
                {
                    b.HasOne("Server.Core.Domain.LeaveRequest", "LeaveRequest")
                        .WithMany("OutboundMessages")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveRequest");
                });

            modelBuilder.Entity("Server.Core.Domain.AppUser", b =>
                {
                    b.Navigation("ClosedClusterCaoAssignments");

                    b.Navigation("ClosedDepartmentChairAssignments");

                    b.Navigation("ClosedEmployeeReportingDepartmentOverrides");

                    b.Navigation("CreatedAdminAssignments");

                    b.Navigation("CreatedClusterCaoAssignments");

                    b.Navigation("CreatedClusters");

                    b.Navigation("CreatedDepartmentChairAssignments");

                    b.Navigation("CreatedEmployeeReportingDepartmentOverrides");

                    b.Navigation("LeaveRequestActions");

                    b.Navigation("LeaveRequests");

                    b.Navigation("UpdatedDepartmentEmailRoutings");
                });

            modelBuilder.Entity("Server.Core.Domain.Cluster", b =>
                {
                    b.Navigation("ClusterCaoAssignments");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Server.Core.Domain.Department", b =>
                {
                    b.Navigation("DepartmentChairAssignments");

                    b.Navigation("DepartmentEmailRoutings");

                    b.Navigation("EmployeeReportingDepartmentOverrides");
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveRequest", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Days");

                    b.Navigation("OutboundMessages");
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveType", b =>
                {
                    b.Navigation("LeaveRequests");

                    b.Navigation("PayLeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
