// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Core.Data;

#nullable disable

namespace server.core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709202211_TablesForAdminPages")]
    partial class TablesForAdminPages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Core.Domain.AppAdminAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppAdminAssignmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IamId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("IamId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppAdminAssignment_IamId");

                    b.ToTable("AppAdminAssignment");
                });

            modelBuilder.Entity("Server.Core.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)");

                    b.Property<Guid>("EntraObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FirstLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IamId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_AppUser_Email");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUser_EmployeeId")
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("EntraObjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUser_EntraObjectId");

                    b.HasIndex("IamId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUser_IamId")
                        .HasFilter("[IamId] IS NOT NULL");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("Server.Core.Domain.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClusterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.ToTable("Cluster");
                });

            modelBuilder.Entity("Server.Core.Domain.Department", b =>
                {
                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ClusterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastSeenInSourceAt")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("SourceLevel")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkflowMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("DepartmentCode");

                    b.HasIndex("ClusterId")
                        .HasDatabaseName("IX_Department_ClusterId");

                    b.HasIndex("LastSeenInSourceAt")
                        .HasDatabaseName("IX_Department_LastSeenInSourceAt");

                    b.HasIndex("WorkflowMode")
                        .HasDatabaseName("IX_Department_WorkflowMode");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Server.Core.Domain.DepartmentEmailRouting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("UpdatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode")
                        .HasDatabaseName("IX_DepartmentEmailRouting_DepartmentCode");

                    b.HasIndex("UpdatedByAppUserId");

                    b.ToTable("DepartmentEmailRouting");
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ClusterIdSnapshot")
                        .HasColumnType("int");

                    b.Property<string>("CoveragePlan")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("IamId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PayLeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ReportingDepartmentCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ReportingDepartmentNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkflowModeSnapshot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .HasDatabaseName("IX_LeaveRequest_AppUserId");

                    b.HasIndex("IamId")
                        .HasDatabaseName("IX_LeaveRequest_IamId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("PayLeaveTypeId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_LeaveRequest_Status");

                    b.HasIndex("ReportingDepartmentCodeSnapshot", "Status")
                        .HasDatabaseName("IX_LeaveRequest_Department_Status");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_LeaveRequest_DateRange");

                    b.ToTable("LeaveRequest");
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveRequestAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int?>("ActorAppUserId")
                        .HasColumnType("int");

                    b.Property<string>("ActorIamId")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsSelfAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("LeaveRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActionAt")
                        .HasDatabaseName("IX_LeaveRequestAction_ActionAt");

                    b.HasIndex("ActorAppUserId")
                        .HasDatabaseName("IX_LeaveRequestAction_ActorAppUserId");

                    b.HasIndex("LeaveRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_LeaveRequestAction_LeaveRequestId");

                    b.ToTable("LeaveRequestAction");
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HasAccrualBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LeaveTypeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SourceLeaveTypeNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeKey")
                        .IsUnique()
                        .HasDatabaseName("UX_LeaveType_LeaveTypeKey");

                    b.HasIndex("SourceLeaveTypeNumber")
                        .HasDatabaseName("IX_LeaveType_SourceLeaveTypeNumber");

                    b.ToTable("LeaveType");
                });

            modelBuilder.Entity("Server.Core.Domain.AppAdminAssignment", b =>
                {
                    b.HasOne("Server.Core.Domain.AppUser", "CreatedByAppUser")
                        .WithMany("CreatedAdminAssignments")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByAppUser");
                });

            modelBuilder.Entity("Server.Core.Domain.Cluster", b =>
                {
                    b.HasOne("Server.Core.Domain.AppUser", "CreatedByAppUser")
                        .WithMany("CreatedClusters")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByAppUser");
                });

            modelBuilder.Entity("Server.Core.Domain.Department", b =>
                {
                    b.HasOne("Server.Core.Domain.Cluster", "Cluster")
                        .WithMany("Departments")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("Server.Core.Domain.DepartmentEmailRouting", b =>
                {
                    b.HasOne("Server.Core.Domain.Department", null)
                        .WithMany("DepartmentEmailRoutings")
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.AppUser", null)
                        .WithMany("UpdatedDepartmentEmailRoutings")
                        .HasForeignKey("UpdatedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveRequest", b =>
                {
                    b.HasOne("Server.Core.Domain.AppUser", null)
                        .WithMany("LeaveRequests")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.LeaveType", null)
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.LeaveType", null)
                        .WithMany("PayLeaveRequests")
                        .HasForeignKey("PayLeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveRequestAction", b =>
                {
                    b.HasOne("Server.Core.Domain.AppUser", null)
                        .WithMany("LeaveRequestActions")
                        .HasForeignKey("ActorAppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Server.Core.Domain.LeaveRequest", null)
                        .WithMany("Actions")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Core.Domain.AppUser", b =>
                {
                    b.Navigation("CreatedAdminAssignments");

                    b.Navigation("CreatedClusters");

                    b.Navigation("LeaveRequestActions");

                    b.Navigation("LeaveRequests");

                    b.Navigation("UpdatedDepartmentEmailRoutings");
                });

            modelBuilder.Entity("Server.Core.Domain.Cluster", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Server.Core.Domain.Department", b =>
                {
                    b.Navigation("DepartmentEmailRoutings");
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveRequest", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Server.Core.Domain.LeaveType", b =>
                {
                    b.Navigation("LeaveRequests");

                    b.Navigation("PayLeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
