// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Core.Data;

#nullable disable

namespace server.core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708153617_ClusterDepartment")]
    partial class ClusterDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Core.Domain.AppAdminAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppAdminAssignmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IamId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("IamId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppAdminAssignment_IamId");

                    b.ToTable("AppAdminAssignment");
                });

            modelBuilder.Entity("Server.Core.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)");

                    b.Property<Guid>("EntraObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FirstLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IamId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_AppUser_Email");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUser_EmployeeId")
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("EntraObjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUser_EntraObjectId");

                    b.HasIndex("IamId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUser_IamId")
                        .HasFilter("[IamId] IS NOT NULL");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("Server.Core.Domain.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClusterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAppUserId");

                    b.ToTable("Cluster");
                });

            modelBuilder.Entity("Server.Core.Domain.Department", b =>
                {
                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ClusterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastSeenInSourceAt")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("SourceLevel")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkflowMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("DepartmentCode");

                    b.HasIndex("ClusterId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Server.Core.Domain.AppAdminAssignment", b =>
                {
                    b.HasOne("Server.Core.Domain.AppUser", "CreatedByAppUser")
                        .WithMany("CreatedAdminAssignments")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByAppUser");
                });

            modelBuilder.Entity("Server.Core.Domain.Cluster", b =>
                {
                    b.HasOne("Server.Core.Domain.AppUser", "CreatedByAppUser")
                        .WithMany("CreatedClusters")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByAppUser");
                });

            modelBuilder.Entity("Server.Core.Domain.Department", b =>
                {
                    b.HasOne("Server.Core.Domain.Cluster", "Cluster")
                        .WithMany("Departments")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("Server.Core.Domain.AppUser", b =>
                {
                    b.Navigation("CreatedAdminAssignments");

                    b.Navigation("CreatedClusters");
                });

            modelBuilder.Entity("Server.Core.Domain.Cluster", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
